project:
  type: website
  output-dir: _site

website:
  title: ""
  navbar:
    logo: ../logo_modules.png
    logo-alt: "Appalachian A.I. Corps logo."  
    left:
      - text: "Water Quality Index"
        href: index
      - text: "Water Quality Lessons"
        menu:
          - text: "L1: Statistics"
            href: 1-statistics/index
          - text: "L2: Predictive Modeling"
            href: 2-predictive-modeling/index
          - text: "L3: Gradient Updates"
            href: 3-gradient-updates/index
          - text: "L4: CNNs"
            href: 4-cnn/index
          - text: "L5: Sensor Data"
            href: 5-sensor-data/index
          - text: "L6: GIS Mapping"
            href: 6-gis/index
    right:
      - text: "AAIC Home"
        href: ../../
      - text: "AAIC Modules"
        href: ../../modules
      - text: "Contact"
        href: ../../contact

  sidebar:
    - title: "Lesson 1: Statistics" 
      id: lesson-1
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - <b>Lesson Outline</b>
        - text: "1. Introduction"
          href: 1-statistics/introduction
        - text: "2. Mean and SD"
          href: 1-statistics/mean-sd
        - text: "3. Median and Range"
          href: 1-statistics/median-range
        - text: "4. Outliers"
          href: 1-statistics/outliers
        - text: "5. Scatterplots"
          href: 1-statistics/scatterplots
        - text: "6. Exercises"
          href: 1-statistics/exercises


format:
  html:
    theme: 
      - united
      - ../customize-theme.scss
    toc: true
    toc-location: right
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
  live-html:
    theme: 
      - united
      - ../customize-theme.scss
    toc: true
    toc-location: right