project:
  type: website
  output-dir: _site

website:
  title: ""
  navbar:
    logo: aaic_letters.png
    logo-alt: "Appalachian A.I. Corps logo."  
    left:
      - text: "Water Quality Lessons"
        menu:
          - text: "L1: Statistics"
            href: 1-statistics/index
          - text: "L2: Predictive Modeling"
            href: 2-predictive-modeling/index
          - text: "L3: Gradient Updates"
            href: 3-gradient-updates/index
          - text: "L4: CNNs"
            href: 4-cnn/index
          - text: "L5: Sensor Data"
            href: 5-sensor-data/index
          - text: "L6: GIS Mapping"
            href: 6-gis/index
    right:
      - text: "AAIC Home"
        href: ../../
      - text: "AAIC Modules"
        href: ../../modules
      - text: "Contact"
        href: ../../contact

  sidebar:
    - title: "Lesson 1: Statistics" 
      id: lesson-1
      style: "floating"
      collapse-level: 2
      align: left
      contents:
        - <b>Lesson Contents</b>
        - text: "1. Overview"
          href: 1-statistics/
        - text: "2. Intro to Water Quality"
          href: 1-statistics/intro-water-quality
        - text: "3. Nitrates Lab"
          href: 1-statistics/nitrates-lab
        - text: "---"
        - text: "4. Intro to Statistics"
          href: 1-statistics/intro-statistics
        - text: "5. Python: Lists"
          href: 1-statistics/python-lists
        - text: "6. Python: Center & Spread"
          href: 1-statistics/center-spread
        - text: "6. Histograms"
          href: 1-statistics/histograms
        - text: "7. Boxplots & Outliers"
          href: 1-statistics/boxplots-outliers
        - text: "---"
        - text: "8. Exercises"
          href: 1-statistics/exercises


format:
  html:
    link-external-newwindow: true
    link-external-icon: true
    theme: united
    toc: true
    toc-location: right
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">
  live-html:
    link-external-newwindow: true
    link-external-icon: true
    theme: 
      - united
      - ../custom-module-theme.scss
    toc: true
    toc-location: right