project:
  type: website
  output-dir: _site

website:
  title: "Appalachian A.I. Corps"
  navbar:
    logo: assets/logo.png
    logo-alt: "Appalachian A.I. Corps logo." 
    background: "#ffffff"
    foreground: "#00746f"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Modules"
        menu:
          - text: "Water Quality"
            href: modules/water-quality/
    right:
      - text: "About"
        href: "#"
      - text: "Modules"
        href: "#"
      - text: "Contact"
        href: "#"

format:
  html:
    theme: united
    css: styles.css
    toc: false
