project:
  type: website
  output-dir: _site

website:
  title: "Appalachian A.I. Corps"
  navbar:
    logo: assets/logo_white.png
    logo-alt: "Appalachian A.I. Corps logo." 
    background: "#006C93"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Modules"
        menu:
          - text: "Water Quality"
            href: modules/water-quality/
    right:
      - text: "About"
        href: "#"
      - text: "Modules"
        href: "#"
      - text: "Contact"
        href: "#"

format:
  html:
    theme: united
    css: styles.css
    toc: false
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">