project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "!modules/**"

website:
  title: "Appalachian A.I. Corps"
  navbar:
    logo: assets/logo.png
    logo-alt: "Appalachian A.I. Corps logo." 
    background: "#ffffff"
    foreground: "#00746f"
    right:
      - text: "Home"
        href: "/"
      - text: "Modules"
        href: modules
      - text: "Contact"
        href: contact
      - text: "Contributors"
        href: contributors

format:
  html:
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">  
    theme: none
    css: styles-main.css
    anchor-sections: false
