project:
  type: website
  output-dir: _site

website:
  title: "Appalachian A.I. Corps"
  navbar:
    logo: assets/logo.png
    logo-alt: "Appalachian A.I. Corps logo." 
    background: "#ffffff"
    foreground: "#00746f"
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lessons"
        menu:
          - text: "Water Quality"
            href: modules/water-quality/
    right:
      - text: "Home"
        href: "/"
      - text: modules.qmd
        href: "#"
      - text: contact.qmd
        href: "#"

format:
  html:
    include-in-header:
      text: |
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap" rel="stylesheet">  
    theme: none
    css: styles-main.css
    toc: false
    anchor-sections: false
